name: Bug Report
description: Report a bug in Anno
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the issue
      placeholder: |
        1. Start Anno with `npm start`
        2. Send request to `POST /v1/content/fetch`
        3. ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Anno version
      placeholder: "1.0.0"
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: Node.js version
      placeholder: "v22.x"
    validations:
      required: true
  - type: dropdown
    id: interface
    attributes:
      label: Interface
      options:
        - HTTP API
        - CLI
        - MCP
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Paste any relevant log output
      render: shell
